export const containersConfig: {
    statusBarDevToolsName: string,
    statusBarDevToolsTitle: string,
    statusBarDevToolsCommand: string,
    statusBarDevToolsCredentialBUName: string,
    statusBarDevToolsCredentialBUTitle: string,
    statusBarDevToolsCredentialBUCommand: string,
    statusBarDevToolsCommandName: string,
    statusBarDevToolsCommandTitle: string,
    statusBarDevToolsCommandCommand: string,
    statusBarDevToolsInitializeName: string,
    statusBarDevToolsInitializeTitle: string,
    statusBarDevToolsInitializeCommand: string,
    contextMenuRetrieveCommand: string,
    contextMenuDeployCommand: string
} = {
    statusBarDevToolsName: "devtoolsmcdev",
    statusBarDevToolsTitle: "mcdev",
    statusBarDevToolsCommand: "sfmc-devtools-vscext.devtoolsSBMcdev",
    statusBarDevToolsCredentialBUName: "devtoolscredentialbu",
    statusBarDevToolsCredentialBUTitle: "Credential/BU",
    statusBarDevToolsCredentialBUCommand: "sfmc-devtools-vscext.devtoolsSBCredentialBU",
    statusBarDevToolsCommandName: "devtoolscommand",
    statusBarDevToolsCommandTitle: "Command",
    statusBarDevToolsCommandCommand: "sfmc-devtools-vscext.devtoolsSBCommand",
    statusBarDevToolsInitializeName: "devtoolsinitialize",
    statusBarDevToolsInitializeTitle: "Initialize",
    statusBarDevToolsInitializeCommand: "sfmc-devtools-vscext.devtoolsSBInitialize",
    contextMenuRetrieveCommand: "sfmc-devtools-vscext.devtoolsCMRetrieve",
    contextMenuDeployCommand: "sfmc-devtools-vscext.devtoolsCMDeploy"
};